# For local testing

services:
  # AUTH SERVICE
  auth:
    image: !reset null
    build:
      context: https://github.com/tazama-lf/auth-service.git#${AUTH_SERVICE_BRANCH}
      args:
        - GH_TOKEN
