# Rule 903 - Large Transaction Detection
services:
  rule-903:
    image: rule-903:local
    env_file:
      - env/rule-903.env
      - .env
    environment:
      - CONFIGURATION_DATABASE_USER=postgres
      - CONFIGURATION_DATABASE_PASSWORD=unused
      - EVENT_HISTORY_DATABASE_USER=postgres
      - EVENT_HISTORY_DATABASE_PASSWORD=unused
      - RAW_HISTORY_DATABASE_USER=postgres
      - RAW_HISTORY_DATABASE_PASSWORD=unused
    restart: always
    networks:
      - tazama_default

networks:
  tazama_default:
    external: true
